# Testes replicáveis, estratificação e lendo dados da internet

In [6]:
# leitura dos dados

uri_tracking = 'https://gist.githubusercontent.com/guilhermesilveira/b9dd8e4b62b9e22ebcb9c8e89c271de4/raw/c69ec4b708fba03c445397b6a361db4345c83d7a/tracking.csv'
uri_projetos = 'https://gist.github.com/guilhermesilveira/12291c548acaf544596795709020e3db'

In [7]:
import pandas as pd

dados = pd.read_csv(uri_tracking)
dados.head()

   inicial  palestras  contato  comprou  patrocinio
0        1          1        0        0           0
1        1          1        0        0           0
2        1          1        0        0           0
3        1          1        0        0           0
4        1          1        0        0           0

In [8]:
y = dados['comprou']
x = dados[['inicial', 'palestras', 'contato', 'patrocinio']]

In [9]:
dados.shape

(99, 5)

In [13]:
treino_x = x[:75]
treino_y = y[:75]

teste_x = x[75:]
teste_y = y[75:]

print(f'Tamanho do treino: {len(treino_x)}')
print(f'Tamanho do teste: {len(teste_x)}')

Tamanho do treino: 75
Tamanho do teste: 24

In [17]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes)
print(f'A acurácia do modelo é: {acuracia * 100:.2f}%')

A acurácia do modelo é: 95.83%

## Estratificação

In [32]:
from sklearn.model_selection import train_test_split

seed = 218

treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, random_state=seed, stratify=y)

print(f'Tamanho do treino: {len(treino_x)}')
print(f'Tamanho do teste: {len(teste_x)}')

modelo = LinearSVC()
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes)
print(f'A acurácia do modelo é: {acuracia * 100:.2f}%')

Tamanho do treino: 74
Tamanho do teste: 25
A acurácia do modelo é: 92.00%

In [33]:
treino_y.value_counts()

comprou
0    49
1    25
Name: count, dtype: int64

In [34]:
teste_y.value_counts()

comprou
0    17
1     8
Name: count, dtype: int64